// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/secretmanager/v1/secret_manager.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name identifier for this secret
	SecretName string `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	// The actual secret data to split and store
	SecretData []byte `protobuf:"bytes,2,opt,name=secret_data,json=secretData,proto3" json:"secret_data,omitempty"`
	// Number of shares to create (N)
	TotalShares int32 `protobuf:"varint,3,opt,name=total_shares,json=totalShares,proto3" json:"total_shares,omitempty"`
	// Minimum shares needed to reconstruct (K)
	Threshold     int32 `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSecretRequest) Reset() {
	*x = StoreSecretRequest{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSecretRequest) ProtoMessage() {}

func (x *StoreSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSecretRequest.ProtoReflect.Descriptor instead.
func (*StoreSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{0}
}

func (x *StoreSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *StoreSecretRequest) GetSecretData() []byte {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *StoreSecretRequest) GetTotalShares() int32 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

func (x *StoreSecretRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type StoreSecretResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// IDs of share servers that received shares
	ShareServerIds []string `protobuf:"bytes,3,rep,name=share_server_ids,json=shareServerIds,proto3" json:"share_server_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreSecretResponse) Reset() {
	*x = StoreSecretResponse{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSecretResponse) ProtoMessage() {}

func (x *StoreSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSecretResponse.ProtoReflect.Descriptor instead.
func (*StoreSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{1}
}

func (x *StoreSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StoreSecretResponse) GetShareServerIds() []string {
	if x != nil {
		return x.ShareServerIds
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{2}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretNames   []string               `protobuf:"bytes,1,rep,name=secret_names,json=secretNames,proto3" json:"secret_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretsResponse) GetSecretNames() []string {
	if x != nil {
		return x.SecretNames
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secretmanager_v1_secret_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSecretResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_secretmanager_v1_secret_manager_proto protoreflect.FileDescriptor

const file_proto_secretmanager_v1_secret_manager_proto_rawDesc = "" +
	"\n" +
	"+proto/secretmanager/v1/secret_manager.proto\x12\x10secretmanager.v1\"\x97\x01\n" +
	"\x12StoreSecretRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1f\n" +
	"\vsecret_data\x18\x02 \x01(\fR\n" +
	"secretData\x12!\n" +
	"\ftotal_shares\x18\x03 \x01(\x05R\vtotalShares\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x05R\tthreshold\"s\n" +
	"\x13StoreSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10share_server_ids\x18\x03 \x03(\tR\x0eshareServerIds\"\x14\n" +
	"\x12ListSecretsRequest\"8\n" +
	"\x13ListSecretsResponse\x12!\n" +
	"\fsecret_names\x18\x01 \x03(\tR\vsecretNames\"6\n" +
	"\x13DeleteSecretRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"J\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x02\n" +
	"\x14SecretManagerService\x12Z\n" +
	"\vStoreSecret\x12$.secretmanager.v1.StoreSecretRequest\x1a%.secretmanager.v1.StoreSecretResponse\x12Z\n" +
	"\vListSecrets\x12$.secretmanager.v1.ListSecretsRequest\x1a%.secretmanager.v1.ListSecretsResponse\x12]\n" +
	"\fDeleteSecret\x12%.secretmanager.v1.DeleteSecretRequest\x1a&.secretmanager.v1.DeleteSecretResponseB\"Z hyena-k8s/proto/secretmanager/v1b\x06proto3"

var (
	file_proto_secretmanager_v1_secret_manager_proto_rawDescOnce sync.Once
	file_proto_secretmanager_v1_secret_manager_proto_rawDescData []byte
)

func file_proto_secretmanager_v1_secret_manager_proto_rawDescGZIP() []byte {
	file_proto_secretmanager_v1_secret_manager_proto_rawDescOnce.Do(func() {
		file_proto_secretmanager_v1_secret_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_secretmanager_v1_secret_manager_proto_rawDesc), len(file_proto_secretmanager_v1_secret_manager_proto_rawDesc)))
	})
	return file_proto_secretmanager_v1_secret_manager_proto_rawDescData
}

var file_proto_secretmanager_v1_secret_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_secretmanager_v1_secret_manager_proto_goTypes = []any{
	(*StoreSecretRequest)(nil),   // 0: secretmanager.v1.StoreSecretRequest
	(*StoreSecretResponse)(nil),  // 1: secretmanager.v1.StoreSecretResponse
	(*ListSecretsRequest)(nil),   // 2: secretmanager.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 3: secretmanager.v1.ListSecretsResponse
	(*DeleteSecretRequest)(nil),  // 4: secretmanager.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 5: secretmanager.v1.DeleteSecretResponse
}
var file_proto_secretmanager_v1_secret_manager_proto_depIdxs = []int32{
	0, // 0: secretmanager.v1.SecretManagerService.StoreSecret:input_type -> secretmanager.v1.StoreSecretRequest
	2, // 1: secretmanager.v1.SecretManagerService.ListSecrets:input_type -> secretmanager.v1.ListSecretsRequest
	4, // 2: secretmanager.v1.SecretManagerService.DeleteSecret:input_type -> secretmanager.v1.DeleteSecretRequest
	1, // 3: secretmanager.v1.SecretManagerService.StoreSecret:output_type -> secretmanager.v1.StoreSecretResponse
	3, // 4: secretmanager.v1.SecretManagerService.ListSecrets:output_type -> secretmanager.v1.ListSecretsResponse
	5, // 5: secretmanager.v1.SecretManagerService.DeleteSecret:output_type -> secretmanager.v1.DeleteSecretResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_secretmanager_v1_secret_manager_proto_init() }
func file_proto_secretmanager_v1_secret_manager_proto_init() {
	if File_proto_secretmanager_v1_secret_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_secretmanager_v1_secret_manager_proto_rawDesc), len(file_proto_secretmanager_v1_secret_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_secretmanager_v1_secret_manager_proto_goTypes,
		DependencyIndexes: file_proto_secretmanager_v1_secret_manager_proto_depIdxs,
		MessageInfos:      file_proto_secretmanager_v1_secret_manager_proto_msgTypes,
	}.Build()
	File_proto_secretmanager_v1_secret_manager_proto = out.File
	file_proto_secretmanager_v1_secret_manager_proto_goTypes = nil
	file_proto_secretmanager_v1_secret_manager_proto_depIdxs = nil
}
