{{- if .Values.demoApp.enabled }}
{{- if .Values.demoApp.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyena.serviceAccountName" . }}
  labels:
    {{- include "hyena.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo-app
{{- end }}
{{- end }}
