{{- if .Values.secretManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyena.fullname" . }}-secret-manager
  labels:
    {{- include "hyena.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-manager
spec:
  type: {{ .Values.secretManager.service.type }}
  {{- if and (eq .Values.secretManager.service.type "NodePort") .Values.secretManager.service.nodePort }}
  ports:
  - port: {{ .Values.secretManager.port }}
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.secretManager.service.nodePort }}
  - port: {{ .Values.secretManager.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  {{- else }}
  ports:
  - port: {{ .Values.secretManager.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.secretManager.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  {{- end }}
  selector:
    {{- include "hyena.secretManager.selectorLabels" . | nindent 4 }}
{{- end }}
