// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/shareservice/v1/share.proto

package sharev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetShareRequest contains the identity of the requester
type GetShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester_identity is the ServiceAccount identity (namespace:sa-name)
	RequesterIdentity string `protobuf:"bytes,1,opt,name=requester_identity,json=requesterIdentity,proto3" json:"requester_identity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetShareRequest) Reset() {
	*x = GetShareRequest{}
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareRequest) ProtoMessage() {}

func (x *GetShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareRequest.ProtoReflect.Descriptor instead.
func (*GetShareRequest) Descriptor() ([]byte, []int) {
	return file_proto_shareservice_v1_share_proto_rawDescGZIP(), []int{0}
}

func (x *GetShareRequest) GetRequesterIdentity() string {
	if x != nil {
		return x.RequesterIdentity
	}
	return ""
}

// GetShareResponse contains the encrypted share data
type GetShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// share is the secret share data
	Share []byte `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	// server_id identifies which share server this is
	ServerId      string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareResponse) Reset() {
	*x = GetShareResponse{}
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareResponse) ProtoMessage() {}

func (x *GetShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareResponse.ProtoReflect.Descriptor instead.
func (*GetShareResponse) Descriptor() ([]byte, []int) {
	return file_proto_shareservice_v1_share_proto_rawDescGZIP(), []int{1}
}

func (x *GetShareResponse) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *GetShareResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// HealthCheckRequest is empty
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_shareservice_v1_share_proto_rawDescGZIP(), []int{2}
}

// HealthCheckResponse indicates server health
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy indicates if the server is ready to serve shares
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// server_id identifies which share server this is
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// message provides additional health information
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shareservice_v1_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_shareservice_v1_share_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_shareservice_v1_share_proto protoreflect.FileDescriptor

const file_proto_shareservice_v1_share_proto_rawDesc = "" +
	"\n" +
	"!proto/shareservice/v1/share.proto\x12\x0fshareservice.v1\"@\n" +
	"\x0fGetShareRequest\x12-\n" +
	"\x12requester_identity\x18\x01 \x01(\tR\x11requesterIdentity\"E\n" +
	"\x10GetShareResponse\x12\x14\n" +
	"\x05share\x18\x01 \x01(\fR\x05share\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\x14\n" +
	"\x12HealthCheckRequest\"f\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xb9\x01\n" +
	"\fShareService\x12O\n" +
	"\bGetShare\x12 .shareservice.v1.GetShareRequest\x1a!.shareservice.v1.GetShareResponse\x12X\n" +
	"\vHealthCheck\x12#.shareservice.v1.HealthCheckRequest\x1a$.shareservice.v1.HealthCheckResponseB)Z'hyena-k8s/proto/shareservice/v1;sharev1b\x06proto3"

var (
	file_proto_shareservice_v1_share_proto_rawDescOnce sync.Once
	file_proto_shareservice_v1_share_proto_rawDescData []byte
)

func file_proto_shareservice_v1_share_proto_rawDescGZIP() []byte {
	file_proto_shareservice_v1_share_proto_rawDescOnce.Do(func() {
		file_proto_shareservice_v1_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shareservice_v1_share_proto_rawDesc), len(file_proto_shareservice_v1_share_proto_rawDesc)))
	})
	return file_proto_shareservice_v1_share_proto_rawDescData
}

var file_proto_shareservice_v1_share_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shareservice_v1_share_proto_goTypes = []any{
	(*GetShareRequest)(nil),     // 0: shareservice.v1.GetShareRequest
	(*GetShareResponse)(nil),    // 1: shareservice.v1.GetShareResponse
	(*HealthCheckRequest)(nil),  // 2: shareservice.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: shareservice.v1.HealthCheckResponse
}
var file_proto_shareservice_v1_share_proto_depIdxs = []int32{
	0, // 0: shareservice.v1.ShareService.GetShare:input_type -> shareservice.v1.GetShareRequest
	2, // 1: shareservice.v1.ShareService.HealthCheck:input_type -> shareservice.v1.HealthCheckRequest
	1, // 2: shareservice.v1.ShareService.GetShare:output_type -> shareservice.v1.GetShareResponse
	3, // 3: shareservice.v1.ShareService.HealthCheck:output_type -> shareservice.v1.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shareservice_v1_share_proto_init() }
func file_proto_shareservice_v1_share_proto_init() {
	if File_proto_shareservice_v1_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shareservice_v1_share_proto_rawDesc), len(file_proto_shareservice_v1_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shareservice_v1_share_proto_goTypes,
		DependencyIndexes: file_proto_shareservice_v1_share_proto_depIdxs,
		MessageInfos:      file_proto_shareservice_v1_share_proto_msgTypes,
	}.Build()
	File_proto_shareservice_v1_share_proto = out.File
	file_proto_shareservice_v1_share_proto_goTypes = nil
	file_proto_shareservice_v1_share_proto_depIdxs = nil
}
